In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib
import warnings
warnings.filterwarnings('ignore')

In [2]:
matplotlib.rcParams["figure.figsize"]=(20,10)
%matplotlib inline

In [3]:
address='/content/drive/MyDrive/ColabNotebooks/KPMG Virtual Internship/data quality/kpmgdata.xlsx'

In [4]:
c=pd.read_excel(address,sheet_name='CustomerDemographic',header=1)

In [5]:
t=pd.read_excel(address,sheet_name='Transactions',header=1)

In [6]:
c.head()

,customer_id,first_name,last_name,gender,past_3_years_bike_related_purchases,DOB,job_title,job_industry_category,wealth_segment,deceased_indicator,default,owns_car,tenure
0,1,Laraine,Medendorp,F,93,1953-10-12,Executive Secretary,Health,Mass Customer,N,"""'",Yes,11.0
1,2,Eli,Bockman,Male,81,1980-12-16,Administrative Officer,Financial Services,Mass Customer,N,<script>alert('hi')</script>,Yes,16.0
2,3,Arlin,Dearle,Male,61,1954-01-20,Recruiting Manager,Property,Mass Customer,N,2018-02-01 00:00:00,Yes,15.0
3,4,Talbot,NaN,Male,33,1961-10-03,NaN,IT,Mass Customer,N,() { _; } >_[$($())] { touch /tmp/blns.shellsh...,No,7.0
4,5,Sheila-kathryn,Calton,Female,56,1977-05-13,Senior Editor,NaN,Affluent Customer,N,NIL,Yes,8.0

In [7]:
c.drop('default',axis=1,inplace=True)

#checking if there is any customer id in the transactions table that doesnot have a customer information

In [31]:
j1=t.merge(c,how='left',on='customer_id')

In [19]:
c1=t.customer_id 
c2=c.customer_id

In [20]:
c1=sorted(c1)
c2=sorted(c2)

In [21]:
len(c1)

20000

In [22]:
len(c2)

4000

In [28]:
c1[-4]

3500

In [26]:
for i in c1:
  if i not in c2:
    print(i)

5034
5034
5034

hence we see that there is a customer id 5034 in the transactions table about which we get no info in the customerdemographics table

In [29]:
t[t.customer_id==5034]

,transaction_id,product_id,customer_id,transaction_date,online_order,order_status,brand,product_line,product_class,product_size,list_price,standard_cost,product_first_sold_date
8707,8708,0,5034,2017-10-07,0.0,Approved,Solex,Road,medium,medium,416.98,312.735016,2015-08-02
16700,16701,0,5034,2017-01-27,0.0,Approved,Norco Bicycles,Standard,medium,medium,360.40,270.299988,1997-08-25
17468,17469,0,5034,2017-01-03,0.0,Approved,OHM Cycles,Road,medium,medium,742.54,667.400024,1992-10-02

In [30]:
c[c.customer_id==5034]

Empty DataFrame
Columns: [customer_id, first_name, last_name, gender, past_3_years_bike_related_purchases, DOB, job_title, job_industry_category, wealth_segment, deceased_indicator, owns_car, tenure]
Index: []

In [32]:
j1[j1.customer_id==5034]

,transaction_id,product_id,customer_id,transaction_date,online_order,order_status,brand,product_line,product_class,product_size,...,last_name,gender,past_3_years_bike_related_purchases,DOB,job_title,job_industry_category,wealth_segment,deceased_indicator,owns_car,tenure
8707,8708,0,5034,2017-10-07,0.0,Approved,Solex,Road,medium,medium,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
16700,16701,0,5034,2017-01-27,0.0,Approved,Norco Bicycles,Standard,medium,medium,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
17468,17469,0,5034,2017-01-03,0.0,Approved,OHM Cycles,Road,medium,medium,...,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN

#doing the same for address

In [33]:
a=pd.read_excel(address,sheet_name='CustomerAddress',header=1)

In [34]:
c3=sorted(a.customer_id )

In [35]:
for i in c1:
  if i not in c3:
    print(i)

3
3
3
3
3
3
3
3
10
10
10
10
10
10
22
22
22
22
22
22
22
22
23
23
23
23
23
23
23
5034
5034
5034

In [36]:
for i in c2:
  if i not in c3:
    print(i)

3
10
22
23

In [40]:
a[a.customer_id==23]

Empty DataFrame
Columns: [customer_id, address, postcode, state, country, property_valuation]
Index: []